# Generated by Django 4.1 on 2022-09-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_watchlistitems_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitems',
            name='movie_review',
            field=models.TextField(),
        ),
    ]
